version: "3.3"

services:

  # ===== Start OpenCR ======
  mysql-opencr-dev:
    image: mysql:5.7.34
    container_name: mysql-opencr-dev
    env_file:
      - ./opencr/db.env
    ports:
      - "3309:3306"
    volumes:
      - ./opencr/my.cnf:/etc/mysql/my.cnf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  hapi-fhir-dev:
    image: hapiproject/hapi:v5.4.1
    container_name: hapi-fhir-dev
    depends_on:
      - mysql-opencr-dev
    ports:
      - "8085:8080"
    environment:
      spring.config.location: 'file:///user/share/hapi-fhir/application.yaml'
    volumes:
      - ./opencr/application.yaml:/user/share/hapi-fhir/application.yaml
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  es-dev:
    image: intrahealth/elasticsearch:latest
    container_name: es-dev
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  opencr-dev:
    container_name: opencr-dev
    image: intrahealth/opencr:beac58a
    ports:
      - "3000:3000"
    depends_on:
      - hapi-fhir-dev
      - es-dev
    #restart: always
    environment:
      - HAPI_FHIR_URL=tcp://hapi-fhir-dev:8080
    volumes:
      - ./opencr/config_docker.json:/src/server/config/config_docker.json
      - ./opencr/decisionRules.json:/src/server/config/decisionRules.json
      - ./opencr/PatientRelationship.json:/src/resources/Relationships/PatientRelationship.json
      - ./opencr/custom/app.js:/src/server/lib/app.js
      - ./opencr/custom/fhir.js:/src/server/lib/routes/fhir.js
      - ./opencr/server_cert.pem:/src/server/serverCertificates/server_cert.pem
      - ./opencr/server_key.pem:/src/server/serverCertificates/server_key.pem
      - ./opencr/run.sh:/src/server/run.sh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    entrypoint: [ "sh", "run.sh" ]

  # ===== End OpenCR ======

  mysql-central-dev:
    image: mysql:5.6.51
    container_name: mysql-central-dev
    env_file:
      - ./openmrs-common/db.env
    ports:
      - "3307:3306"
    volumes:
      - ./openmrs-central/my.cnf:/etc/mysql/my.cnf
      - ./openmrs-common/openmrs.sql:/docker-entrypoint-initdb.d/openmrs.sql
      - ./openmrs-common/config.sql:/docker-entrypoint-initdb.d/openmrs_config.sql
      - ./openmrs-central/config.sql:/docker-entrypoint-initdb.d/openmrs_config_central.sql
      - ./dbsync-common/mgt_db.sql:/docker-entrypoint-initdb.d/mgt_db.sql
      - ./dbsync-central/mgt_db_config.sql:/docker-entrypoint-initdb.d/mgt_db_config.sql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  mysql-remote-dev:
    image: mysql:5.6.51
    container_name: mysql-remote-dev
    env_file:
      - ./openmrs-common/db.env
    ports:
      - "3308:3306"
    volumes:
      - ./openmrs-remote/my.cnf:/etc/mysql/my.cnf
      - ./openmrs-common/openmrs.sql:/docker-entrypoint-initdb.d/openmrs.sql
      - ./openmrs-common/config.sql:/docker-entrypoint-initdb.d/openmrs_config.sql
      - ./openmrs-remote/config.sql:/docker-entrypoint-initdb.d/openmrs_config_remote.sql
      - ./dbsync-common/mgt_db.sql:/docker-entrypoint-initdb.d/mgt_db.sql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  openmrs-central-dev:
    image: tomcat:7.0.109-jdk8-openjdk-slim
    container_name: openmrs-central-dev
    depends_on:
      - mysql-central-dev
      - artemis-dev
      - opencr-dev
    volumes:
      - ./opencr/server_cert.pem:/usr/local/tomcat/server_cert.pem
      - ./openmrs-common/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./openmrs-common/run.sh:/user/local/tomcat/bin/run_openmrs.sh
      - ./openmrs-central/openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./openmrs-central/openmrs.p12:/root/.OpenMRS/mpi/config/openmrs.p12
      - ./openmrs-common/modules:/root/.OpenMRS/modules
      - ./openmrs-central/modules/debezium-1.0.0-SNAPSHOT.omod:/root/.OpenMRS/modules/debezium.omod
      - ./openmrs-central/modules/mpi-1.0.0-SNAPSHOT.omod:/root/.OpenMRS/modules/mpi.omod
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "8081:8080"
    entrypoint: [ "sh", "/user/local/tomcat/bin/run_openmrs.sh" ]

  openmrs-remote-dev:
    image: tomcat:7.0.109-jdk8-openjdk-slim
    container_name: openmrs-remote-dev
    depends_on:
      - mysql-remote-dev
      - artemis-dev
    volumes:
      - ./opencr/server_cert.pem:/usr/local/tomcat/server_cert.pem
      - ./openmrs-common/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./openmrs-common/run.sh:/user/local/tomcat/bin/run_openmrs.sh
      - ./openmrs-common/modules:/root/.OpenMRS/modules
      - ./openmrs-remote/openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./openmrs-remote/modules/esaudefeatures-1.1.0-SNAPSHOT.416229.omod:/root/.OpenMRS/modules/esaudefeatures.omod
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "8082:8080"
    entrypoint: [ "sh", "/user/local/tomcat/bin/run_openmrs.sh" ]

# ===== Start DB sync ======
  artemis-dev:
    image: cnocorch/activemq-artemis
    container_name: artemis-dev
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./artemis/artemis-roles.properties:/var/lib/artemis/etc/artemis-roles.properties
      - ./artemis/artemis-users.properties:/var/lib/artemis/etc/artemis-users.properties
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  mysql-central-dbsync-dev:
    image: mysql:5.6.51
    container_name: mysql-central-dbsync-dev
    env_file:
      - ./openmrs-common/db.env
    ports:
      - "3310:3306"
    volumes:
      - ./dbsync-common/mgt_db.sql:/docker-entrypoint-initdb.d/mgt_db.sql
      - ./dbsync-central/mgt_db_config.sql:/docker-entrypoint-initdb.d/mgt_db_config.sql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  mysql-remote-dbsync-dev:
    image: mysql:5.6.51
    container_name: mysql-remote-dbsync-dev
    env_file:
      - ./openmrs-common/db.env
    ports:
      - "3311:3306"
    volumes:
      - ./dbsync-common/mgt_db.sql:/docker-entrypoint-initdb.d/mgt_db.sql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  dbsync-central-dev:
    image: adoptopenjdk/openjdk8:alpine-slim
    container_name: dbsync-central-dev
    depends_on:
      - mysql-central-dbsync-dev
      - artemis-dev
    ports:
      - "8083:8081"
    volumes:
      - ./dbsync-central/application.properties:/usr/local/dbsync/application.properties
      - ./dbsync-common/openmrs-eip-app-1.3.0.jar:/usr/local/dbsync/openmrs-eip-app.jar
      - ./dbsync-common/users.properties:/usr/local/dbsync/dbsync-users.properties
      - ./dbsync-common/init.sh:/usr/local/dbsync/init_eip.sh
      - ./dbsync-central/run.sh:/usr/local/dbsync/run.sh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    working_dir: /usr/local/dbsync
    entrypoint: [ "sh", "run.sh" ]

  dbsync-remote-dev:
    image: adoptopenjdk/openjdk8:alpine-slim
    container_name: dbsync-remote-dev
    depends_on:
      - mysql-remote-dbsync-dev
      - artemis-dev
    ports:
      - "8084:8081"
    volumes:
      - ./dbsync-remote/application.properties:/usr/local/dbsync/application.properties
      - ./dbsync-common/openmrs-eip-app-1.3.0.jar:/usr/local/dbsync/openmrs-eip-app.jar
      - ./dbsync-common/users.properties:/usr/local/dbsync/dbsync-users.properties
      - ./dbsync-common/init.sh:/usr/local/dbsync/init_eip.sh
      - ./dbsync-remote/run.sh:/usr/local/dbsync/run.sh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    working_dir: /usr/local/dbsync
    entrypoint: [ "sh", "run.sh" ]
